# See https://github.com/silverstripe/silverstripe-travis-support for setup details

language: php

sudo: false

php:
 - 5.5
 - 5.6
 - 7.0

env:
  - DB=MYSQL CORE_RELEASE=4

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=4 COVERAGE=1

before_script:
 - composer self-update || true
 - phpenv rehash
 - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

script:
  # Execute tests with no coverage
  - "if [ \"$COVERAGE\" != \"1\" ]; then ./vendor/bin/phpunit crontask/tests/; fi"
  # Execute tests with coverage.  Do this for a small
  - "if [ \"$COVERAGE\" = \"1\" ]; then ./vendor/bin/phpunit --coverage-clover=coverage.clover crontask/tests/; fi"

after_script:
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --repository g/${TRAVIS_REPO_SLUG} --revision ${TRAVIS_COMMIT} --format=php-clover coverage.clover
