# See https://github.com/silverstripe/silverstripe-travis-support for setup details

language: php

sudo: false

php:
 - 5.4

env:
  global:
    - CORE_RELEASE=3.1
  matrix:
    - DB=MYSQL

matrix:
  include:
    - php: 5.3
      env: DB=MYSQL

before_script:
  - composer self-update || true
  - phpenv rehash
  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover crontask/tests

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
